### ISSUE TITLE
Syntax highlighting not working properly in grammar rules

### ISSUE THREAD

**Issue by AlessioAtroni** [arthwang/vsc-prolog#28] opened 2018-11-13 11:28 UTC
See pictures' comments for details:

<img width="452" alt="schermata 2018-11-13 alle 12 23 33" src="https://user-images.githubusercontent.com/34690870/48410471-f9383880-e73e-11e8-8ee1-84b8dcbab74a.png">

<img width="448" alt="schermata 2018-11-13 alle 12 25 10" src="https://user-images.githubusercontent.com/34690870/48410563-37cdf300-e73f-11e8-9bfb-b313eb65455e.png">

**Comment by arthwang** [comment] 2018-11-15 01:20
Duplicate of #9

**Closed** 2018-11-15 08:39 UTC
